/* Generated by scripts/content/build-map-v2.ts. */
export const GENERATED_LAYOUT = {
  "layoutRevisions": {
    "northeast_downtown": 1,
    "northwest_residential": 1,
    "southeast_docks": 1,
    "southwest_commercial": 1
  },
  "actorTiles": {
    "protagonist": {
      "mapId": "northwest_residential",
      "locationId": "protagonist_villa",
      "x": 18,
      "y": 18
    },
    "linda": {
      "mapId": "northwest_residential",
      "locationId": "linda_villa",
      "x": 23,
      "y": 28
    },
    "generic_resident": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 29,
      "y": 33
    },
    "linda_boyfriend": {
      "mapId": "northwest_residential",
      "locationId": "linda_villa",
      "x": 25,
      "y": 28
    },
    "mina_park": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 34,
      "y": 15
    },
    "rafael_cruz": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 27,
      "y": 5
    },
    "sora_tan": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 27,
      "y": 20
    },
    "devon_price": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 37,
      "y": 23
    },
    "priya_nair": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 33,
      "y": 36
    },
    "tomas_reed": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 43,
      "y": 36
    },
    "elise_moreau": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 53,
      "y": 36
    },
    "resident_01": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 2,
      "y": 5
    },
    "resident_02": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 4,
      "y": 5
    },
    "resident_03": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 6,
      "y": 5
    },
    "resident_04": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 60,
      "y": 5
    },
    "resident_05": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 2,
      "y": 12
    },
    "resident_06": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 4,
      "y": 12
    },
    "resident_07": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 6,
      "y": 12
    },
    "resident_08": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 60,
      "y": 12
    },
    "resident_09": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 2,
      "y": 20
    },
    "resident_10": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 4,
      "y": 20
    },
    "resident_11": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 6,
      "y": 20
    },
    "resident_12": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 60,
      "y": 20
    },
    "resident_13": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 2,
      "y": 30
    },
    "resident_14": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 4,
      "y": 30
    },
    "resident_15": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 6,
      "y": 30
    },
    "resident_16": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 60,
      "y": 30
    },
    "resident_17": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 2,
      "y": 38
    },
    "resident_18": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 4,
      "y": 38
    },
    "resident_19": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 6,
      "y": 38
    },
    "resident_20": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 60,
      "y": 38
    },
    "resident_21": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 2,
      "y": 44
    },
    "resident_22": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 4,
      "y": 44
    },
    "resident_23": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 6,
      "y": 44
    },
    "resident_24": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 60,
      "y": 44
    }
  },
  "scheduleTiles": {
    "linda_home": {
      "mapId": "northwest_residential",
      "locationId": "linda_villa",
      "x": 23,
      "y": 28
    },
    "linda_relax": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 28,
      "y": 30
    },
    "linda_shop": {
      "mapId": "southwest_commercial",
      "locationId": "southwest_commercial",
      "x": 15,
      "y": 16
    },
    "generic_home": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 29,
      "y": 33
    },
    "generic_work": {
      "mapId": "northwest_residential",
      "locationId": "northwest_residential",
      "x": 27,
      "y": 28
    },
    "generic_meal": {
      "mapId": "northeast_downtown",
      "locationId": "northeast_downtown",
      "x": 44,
      "y": 34
    },
    "generic_nightlife": {
      "mapId": "northeast_downtown",
      "locationId": "northeast_downtown",
      "x": 18,
      "y": 13
    }
  },
  "workTiles": {
    "mina_park": {
      "mapId": "northwest_residential",
      "locationId": "mina_spa",
      "x": 34,
      "y": 15
    },
    "rafael_cruz": {
      "mapId": "southwest_commercial",
      "locationId": "rafael_cafe",
      "x": 46,
      "y": 36
    },
    "sora_tan": {
      "mapId": "southwest_commercial",
      "locationId": "sora_boutique",
      "x": 20,
      "y": 16
    },
    "devon_price": {
      "mapId": "northeast_downtown",
      "locationId": "devon_bar",
      "x": 20,
      "y": 13
    },
    "priya_nair": {
      "mapId": "southeast_docks",
      "locationId": "priya_clinic",
      "x": 18,
      "y": 15
    },
    "tomas_reed": {
      "mapId": "southeast_docks",
      "locationId": "tomas_marina",
      "x": 42,
      "y": 33
    },
    "elise_moreau": {
      "mapId": "northeast_downtown",
      "locationId": "elise_studio",
      "x": 46,
      "y": 36
    }
  },
  "homeVisitTile": {
    "mapId": "northwest_residential",
    "locationId": "protagonist_villa",
    "x": 19,
    "y": 18
  }
} as const;
