import type { TokenFrame } from './character-source';

export const PROTAGONIST_REFERENCE_FRAME_IDS = [
  'front-1',
  'front-2',
  'rear-1',
  'rear-2',
  'left-1',
  'left-2',
  'right-1',
  'right-2',
] as const;

export type ProtagonistReferenceFrameId = typeof PROTAGONIST_REFERENCE_FRAME_IDS[number];

const FRONT = [
  '........................',
  '........................',
  '..........KKKD....KK....',
  '.......KKHhhhHK...KhK...',
  '.....KKHhhhhhhhKKKhhK...',
  '....KHhHHhHHHhhHHhhHK...',
  '....HhHHHhHHHHHhhhHHK...',
  '...KhhHHHHhhhhhhhHHK....',
  '...KHHHHHHHhhhhhHHKK....',
  '...KHHHKsKHHHHHHHKKHK...',
  '...KHHHsssKKKHHHKKHHH...',
  '...KHHKsKKSsssKKssHK....',
  '....KKsSSSSSSSSSSsKK....',
  '...KsKSWKWDSSWKWDSKsK...',
  '...KsKSWKWDSSWKWDSKsK...',
  '....KsSSSSSSSSSSSSsK....',
  '.....KsSSSSssSSSSsK.....',
  '.....KssSSSSSSSsssK.....',
  '....KACKsssssssHKCCK....',
  '...KCCACCCCCCCCCCCCCH...',
  '...KCCCACCCCCCCCCCCCK...',
  '...KCCCAaCCCCCCCCCCCH...',
  '...KCCCCAaCCCCCCCCCCK...',
  '...KCCCCCAACCCCCCCCCH...',
  '...KsCCCCCAACCCCCCCsH...',
  '....KCCCCCCCACCCCCCK....',
  '....KCCCCCCCCAACCCAH....',
  '.....KCCCCCCCCCAAAK.....',
  '......KHHHHHHHHHHK......',
  '.......KKKKKKKKKh.......',
] as const satisfies TokenFrame;

const REAR = [
  '........................',
  '........................',
  '...........KK...........',
  '...KKK...KKhhhKKh.......',
  '...KhhKKKHhhhhhhHK......',
  '...KHhHHhhhhhhhhhHK.....',
  '....KHHhhhhhhhhhhhHK....',
  '.....KHhhhhhhhhhhhhK....',
  '.....KhhhhhhhhhhhhhHK...',
  '....KHhhhhhhhhhhhhhHK...',
  '....KHhhhhhhhhhhhhHHK...',
  '.....KHhhhhhhhhhhhHKK...',
  '.....KHHHHhhhhhhhHHKH...',
  '....KsKHHHHhHHHHHHKsK...',
  '....KsKHHHHHHHHHHHKsK...',
  '.....KKHHHHHHHHHHHKK....',
  '......KKHHHHHHHHHHK.....',
  '......KCKKKKKKKKKCK.....',
  '.....KCACCCCCCCCCCCK....',
  '....KCCCACCCCCCCCCCCK...',
  '....KCCCCACCCCCCCCCCK...',
  '....KCCCCCACCCCCCCCCK...',
  '....KCCCCCCACCCCCCCCK...',
  '....KCCCCCCCACCCCCCCK...',
  '....KsCCCCCCCAACCCCsH...',
  '.....KCCCCCCCCCAACCKH...',
  '.....KCCCCCCCCCCCAAK....',
  '......KCCCCCCCCCCCKH....',
  '.......KHHHHHHHHHKK.....',
  '........KKKKKKKKK.......',
] as const satisfies TokenFrame;

const LEFT = [
  '........................',
  '....KK..................',
  '...KhH...hhhhKK.........',
  '...KhhK.KHhhhhHKK.......',
  '...KHhHKHhhhhhhhHKK.....',
  '....KHhHHhhhhhhhhhHK....',
  '....KHHhHHHhhhhHHhhK....',
  '....KKHhhhhhhhhhhhhhK...',
  '.....KHHHhHHhhhhhhHHK...',
  '.....KKKKKHHHhhhhhHHK...',
  '......KsssKHHHHHHHHHK...',
  '......KsKKsKHHHHHHHHK...',
  '......KSssSsHKKKHHHH....',
  '......KSKWSSHKSsKHHK....',
  '.....KSSKWSSKssSKHK.....',
  '......KSSSSSSSsKHHK.....',
  '......KsSSSSSsssKK......',
  '.......KsssssHKCC.......',
  '.......KKKKCCCCCCK......',
  '.......KCCCCCCCCAK......',
  '.......KCCCCCCCACCH.....',
  '.......KCCCCCCDACCK.....',
  '.......KCCCCCAACCCK.....',
  '.......KCCCCCCCCCCK.....',
  '.......KCCCCCCCCCCK.....',
  '.......KAsSSsCCCCCK.....',
  '.......KAKAsHCCCCK......',
  '........HAKHCCCCK.......',
  '........KHHHHHHK........',
  '.........KKKKKK.........',
] as const satisfies TokenFrame;

const RIGHT = [
  '........................',
  '..................KK....',
  '...........hhHH...KhK...',
  '.......KKKHhhhhKKKHhK...',
  '......KhhHhhhhhhHKhHK...',
  '.....HhhhhhhhhhhHHHHK...',
  '....KhhhhHhhhHHHhhHHK...',
  '...KHhhhhhhhHHhhhhHK....',
  '...KHhhhhhhHHHHHHHHK....',
  '...KHhhhhhhHHHKKKHKK....',
  '...KHHHHHHHHKKssssK.....',
  '...KHHHHHHHHKssKKs......',
  '....HHHHKKHKsSSsss......',
  '....KHHKsSHssSSKSs......',
  '....HHHKSsssSSSKSSK.....',
  '.....KHHKsSSSSSSSs......',
  '......KKssssSSSSSs......',
  '......DCCHsssssssK......',
  '......KACCCCCKKKKK......',
  '......HCACCCCCCCCK......',
  '.....KCCCACCCCCCCK......',
  '.....KCCCACCCCCCCK......',
  '.....KCCCCCCCCCCCK......',
  '.....KCCCCCCCCCCCK......',
  '.....KCCCCCCCCChCK......',
  '.....KCCCCKsSLSHAK......',
  '......KCCCCHsAsACK......',
  '.......KCCCCHKKCH.......',
  '........KHHHHHHK........',
  '.........KKKKKK.........',
] as const satisfies TokenFrame;

const PROTAGONIST_REFERENCE_FRAMES: Readonly<Record<ProtagonistReferenceFrameId, TokenFrame>> =
  Object.freeze({
    'front-1': FRONT,
    'front-2': FRONT,
    'rear-1': REAR,
    'rear-2': REAR,
    'left-1': LEFT,
    'left-2': LEFT,
    'right-1': RIGHT,
    'right-2': RIGHT,
  });

export function protagonistReferenceFrames(
  characterId: string,
): Readonly<Record<ProtagonistReferenceFrameId, TokenFrame>> | undefined {
  return characterId === 'protagonist' ? PROTAGONIST_REFERENCE_FRAMES : undefined;
}
